# Basic Information 
title: Yulong Dou 窦雨龙
position: Graduate Student
affiliation: ShanghaiTech University
subaffiliation: School of Biomedical Engineering
affiliation_link: https://www.shanghaitech.edu.cn/
subaffiliation_link: https://bme.shanghaitech.edu.cn/
email: douyl2023[at]shanghaitech.edu.cn
address: 393 Middle Huaxia Road, Pudong, Shanghai, China
address_link: https://www.google.fr/maps/place/%E4%B8%8A%E6%B5%B7%E7%A7%91%E6%8A%80%E5%A4%A7%E5%AD%A6/@31.1763741,121.5898769,17z/data=!3m1!4b1!4m6!3m5!1s0x35b27828f381499b:0x5ae88f32ad8196b1!8m2!3d31.1763741!4d121.5924518!16s%2Fm%2F0qftcsg?entry=ttu

# Search Engine Optimization (SEO)
keywords: Yulong Dou, yulong dou, Yulong, douyl
canonical: https://minimal-light-theme.yliu.me/
description: Yulong Dou is a graduate student in the School of Biomedical Engineering at ShanghaiTech University.

# The option is used to enable the Johns Hopkins template.
enable_hopkins_logo: false

# The option is used to show the last update time.
enable_last_update: false

# Links
# cv_link: https://blog.songchen.science/de3ec0aa2234aa1e3ee275bbc715c6c9/CV.pdf  !!!!!!!!!!!
github_link: https://github.com/douyl/
google_scholar: https://scholar.google.com/citations?hl=zh-CN&authuser=1&user=2gXabhsAAAAJ
researchgate: https://www.researchgate.net/profile/Yulong-Dou
semantic_scholar: https://www.semanticscholar.org/author/Yulong-Dou/2258957485

# Images 
avatar: ./assets/img/yulong.jpg
favicon: ./assets/img/favicon.png
favicon_dark: ./assets/img/favicon-dark.png

# Footnotes
# Footnote
# You may use the option to disable the footnote, "Powered by Jekyll and Minimal Light theme."
enable_footnote: false
#footnote: Feel free to use my website's source code.
#footnote_link: https://github.com/yaoyao-liu/minimal-light


# Google Analytics ID
# Please remove this if you don't use Google Analytics
google_analytics: ${{ secrets.GOOGLE_SCHOLAR_ID }}

# Use this project as a remote theme for GitHub Pages
# See the guide here: https://docs.github.com/en/pages/setting-up-a-github-pages-site-with-jekyll/adding-a-theme-to-your-github-pages-site-using-jekyll
remote_theme: yaoyao-liu/minimal-light

plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one


# The following files will be removed from the generated website.
exclude:
  - build.sh
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - CNAME
